<?php

return array(
    "މުހައްމަދު" => "Mohamed",
    "އަހްމަދު" => "Ahmed",
    "އެއާޕޯޓް" => "airport",
    "އިންސްޓިޓިއުޓް" => "institute",
    "އެތުލެޓިކްސ" => "athletics",
    "އެތްލެޓިކްސ" => "athletics",
    "ޖޫނިއާ" => "junior",
    "އެސޯސިއޭޝަނ" => "association",
    "މޯލްޑިވްސ" => "Maldives",
    "މޯލްޑިވުސ" => "Maldives",
    "ޖެނުވަރީ" => "january",
    "ފެބުރުވަރީ" => "february",
    "މާޗް" => "march",
    "މާރިޗ" => "march",
    "އެޕްރީލ" => "april",
    // "" => "may",
    "ޖޫން" => "june",
    "ޖުލައި" => "july",
    "އޮގަސްޓ" => "august",
    "ސެޕްޓެމްބަރ" => "september",
    "އޮކްޓޯބަރ" => "october",
    "ނޮވެމްބަރ" => "november",
    "ޑިސެމްބަރ" => "december",
    "ކަލަންޑަރ" => "calendar",
    "ޗެމްޕިއަންޝިޕ" => "championship",
    "ޓުއަރިޒަމ" => "tourism",
    "ޓޫރިސްޓ" => "tourist",
    "ގުރުއާނ" => "quran",
    "ޤުރުއާނ" => "quran",
    "ރިކޯޑު" => "record",
    "މޭޔަރ" => "mayor",
    "ސިޓީ ކައުންސިލ" => "city council",
    "ކައުންސިލ" => "council",
    "ވޯޓު" => "vote",
    "ޓާމިނަލ" => "terminal",
    "އެވޯޑް" => "award",
    "އިވެންޓ" => "event",
    "ސްޕޮންސަރ" => "sponsor",
);
